### ISSUE TITLE
SSR for SEO

### ISSUE THREAD

**Issue by bitomule** [meteorhacks/meteor-ssr#11]
I'm working on a meteor app with only 4 pages that should be served to search bots. I'm trying to use SSR for this, just give bots an static page rendered in server and client rendered page for users.

Any idea on how can I do this?

I'm using iron router, btw.

**Comment by ashishgupta2** [comment]
Not sure if you checked this out yet. 

https://meteorhacks.com/meteor-server-sider-rendering-for-seo-purpose.html

**Comment by bitomule** [comment]
Yeah, thanks @ashishgupta2
