### ISSUE TITLE
use <br> and any other html tags inside template?

### ISSUE THREAD

**Issue by voidale** [meteorhacks/meteor-ssr#30]
Can I return html tags inside handlebars helpers? I'm having a problem it seems they are all converted to plaintext, Not sure if this possible?

**Comment by Ethaan** [comment]
Same here , did you fix it?

**Comment by arunoda** [comment]
I think Blaze does not support them. You need to use `{{{yourHelper}}}` to get them as html.

**Comment by Ethaan** [comment]
On my scenario i want to send the server template compiled in html changing text to html fix this.

Related [SO](http://stackoverflow.com/questions/28793474/html-in-emails-not-rendering/30551747#30551747)

**Comment by voidale** [comment]
Yes it's fixed long time ago arunoda is right you need to use it as `{{{ }}}` it's handlebars thing.
