### ISSUE TITLE
Emails rendered with SSR not showing in certain email clients

### ISSUE THREAD

**Issue by valzam** [meteorhacks/meteor-ssr#32]
Hey,

we are using SSR to render certain email templates on the server (automatic notifications tied to a period task). For some reason they are not getting displayed (empty message) in the following email clients:

Apple Mail 8
IOs8
Thunderbird

All other email clients are fine. We also render emails on the client which get displayed without a problem, so the problem definitely is with SSR. I know that this is a very specific question, but maybe you/someone still has an idea what might be causing this issue.

**Comment by kevinm90** [comment]
Probably you already fixed it, but for everyone coming across this topic in the future:
Don't use the template-Tag at the beginning of your html-File.
