### ISSUE TITLE
Caching compiled template

### ISSUE THREAD

**Issue by jstoeffler** [meteorhacks/meteor-ssr#38]
Hi,

I had a quick look at the code, and it looks like the template is compiled every time `SSR.compileTemplate` is called.

I'm using this package to send emails, and sometimes I send a lot of them, so I think it would be interesting to keep the result in memory.

So two questions:
- Is that something you could add?
- Until then, or if it's not part of the plan, it safe for me to call `SSR.compileTemplate` just once before the batch email sending? (or better, can I check whether the template is compiled? or any better idea?)

**Comment by arunoda** [comment]
You don't need to compile it every time. Just need to compile once. Then render it.

**Comment by jstoeffler** [comment]
Yes, I just noticed that :)

Actually I was just unsure whether the template would be kept in memory, but I've seen I can keep the result of `compileTemplate` in a variable and use it in the `render` function, which feels safer.

Thanks for the quick answer
