### ISSUE TITLE
Compile HTML with inline CSS

### ISSUE THREAD

**Issue by gwendall** [meteorhacks/meteor-ssr#8]
Is there an easy way to get HTML templates compiled with their related styles inline? Ie having all their children DOM elements' "style" attributes populated with the appropriate data from CSS. That would be pretty great for emails.

**Comment by robertclarkson** [comment]
Try using this node package "Juice" wrapped by sacha:

https://atmospherejs.com/sacha/juice

https://www.npmjs.com/package/juice
